### ISSUE TITLE
Building on Ubuntu

### ISSUE THREAD

**Issue by Copyrites** [Rupan/BDInfo#1] opened 2016-07-30 13:12 UTC
On Ubuntu 16.04 (xenial) I was getting errors like this:

CSC: error CS0518: The predefined type `System.Object' is not defined or imported

CSC: error CS0518: The predefined type `System.ValueType' is not defined or imported

CSC: error CS0518: The predefined type `System.Attribute' is not defined or imported

Using this build line made it compile successfully (but with warnings):

xbuild /p:Configuration=Release BDInfo.csproj /p:TargetFrameworkVersion="v4.5"

**Comment by Musashii-kun** [comment] 2016-07-31 07:48
I see the same build errors on the Mono packages that ship with Ubuntu 16.04.

I confirmed a couple of hours ago that the code builds fine using Visual Studio 2015, targeting .NET 2.0.  It shouldn't be necessary to target framework version 4.5, the code uses none of its features.

It might be that the Mono version in Ubuntu still isn't up to spec and you need to install the upstream version.  I remember similar issues with Ubuntu 15.04, but I haven't yet confirmed with 16.04.  If you have time, can you try to build with the upstream Mono packages?

**Comment by Copyrites** [comment] 2016-07-31 11:31
I tried the upstream and that compiles  ok without the  /p:TargetFrameworkVersion="v4.5"

I thought I had used the upstream (because that's what your instructions said to do) but it turned out that I had added the repository, but the "apt upgrade" didn't pick it up. And I didn't verify.

Still, it might be useful to change the readme so users won't have to install the upstream since adding the target framework seems to work equally as well.

**Comment by Musashii-kun** [comment] 2016-07-31 20:17
I think it isn't a good idea to specify v4.5 since the code is written for 2.0.  Specifying a later version will work but will likely prevent the compiled executable from running on machines with older .NET installations. I'll see if I can get it to work with the stock mono version when specifying v2.0 and update the build instructions accordingly.

I think I'll also try to get the debian packaging to work and write a desktop file for easy use.

**Comment by Musashii-kun** [comment] 2016-08-01 06:44
The compile failures appear to be in the version of ZedGraph shipped as a part of this package.  I'll see how difficult it would be to update to a newer version.

**Comment by Musashii-kun** [comment] 2016-11-26 05:25
After reading over some other Mono code I realized that I was wrong to say that v4.5 is too new.  If anyone is still using 2.0 then they have more urgent issues to attend to.  I've just committed changes to the develop branch which set the default framework to v4.5 and the code appears to build correctly now as stated in the README.

Thanks for the bug report.  Issue resolved :)

**Closed as completed by Musashii-kun** 2016-11-26 05:25 UTC
